# Generated by Django 5.1.6 on 2025-09-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
