# Generated by Django 5.1.6 on 2025-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crop_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='fertilizer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_months',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='irrigation_liters',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='pesticide',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sowing_months',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sunlight_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
