# Generated by Django 5.1.6 on 2025-09-13 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crop_fertilizer_crop_harvesting_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_type',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='soil_type',
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('did_irrigate', models.BooleanField(default=False)),
                ('did_fertilize', models.BooleanField(default=False)),
                ('did_apply_pesticide', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.crop')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('crop', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
