# Generated by Django 5.1.6 on 2025-09-15 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_crop_irrigation_type_remove_crop_soil_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='category',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('ROUTINE', 'Routine'), ('TIP', 'Tip')], default='TIP', max_length=10),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
