# Generated by Django 5.1.6 on 2025-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acreage',
            field=models.CharField(blank=True, choices=[('<1', '1 ഏക്കറിൽ താഴെ'), ('>1', '1 ഏക്കറിൽ കൂടുതൽ')], max_length=10, null=True),
        ),
    ]
