# Generated by Django 5.1.6 on 2025-09-13 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_acreage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation_type', models.CharField(blank=True, choices=[('drip', 'Drip'), ('flood', 'Flood'), ('sprinkler', 'Sprinkler'), ('rainfed', 'Rainfed')], max_length=20, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('sown_date', models.DateField(blank=True, null=True)),
                ('harvested_date', models.DateField(blank=True, null=True)),
                ('is_sown', models.BooleanField(default=False)),
                ('is_harvested', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_type', models.CharField(choices=[('weather', 'Weather'), ('market', 'Market'), ('disease', 'Disease'), ('general', 'General')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='accounts.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.crop')),
            ],
        ),
    ]
