# Generated by Django 5.1.6 on 2025-09-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_crop_advisory_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisory',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Advisory',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
