# Generated by Django 5.1.6 on 2025-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_advisory_crop_remove_crop_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acreage',
            field=models.CharField(choices=[('<1', '1 ഏക്കറിൽ താഴെ'), ('>1', '1 ഏക്കറിൽ കൂടുതൽ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('തിരുവനന്തപുരം', 'തിരുവനന്തപുരം'), ('കൊല്ലം', 'കൊല്ലം'), ('പത്തനംതിട്ട', 'പത്തനംതിട്ട'), ('ആലപ്പുഴ', 'ആലപ്പുഴ'), ('കോട്ടയം', 'കോട്ടയം'), ('ഇടുക്കി', 'ഇടുക്കി'), ('എറണാകുളം', 'എറണാകുളം'), ('ത്രിശ്ശൂർ', 'ത്രിശ്ശൂർ'), ('പാലക്കാട്', 'പാലക്കാട്'), ('മലപ്പുറം', 'മലപ്പുറം'), ('കോഴിക്കോട്', 'കോഴിക്കോട്'), ('വയനാട്', 'വയനാട്'), ('കണ്ണൂർ', 'കണ്ണൂർ'), ('കാസർഗോഡ്', 'കാസർഗോഡ്')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='soil_type',
            field=models.CharField(choices=[('മണൽ', 'മണൽ'), ('ചെങ്കൽ', 'ചെങ്കൽ'), ('കറുത്ത മണ്ണ്', 'കറുത്ത മണ്ണ്'), ('ചെങ്കൽ മണ്ണ്', 'ചെങ്കൽ മണ്ണ്'), ('അല്ലുവിയൽ', 'അല്ലുവിയൽ')], max_length=50),
        ),
    ]
