# Generated by Django 5.1.6 on 2025-09-19 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ml', models.TextField(help_text='Question in Malayalam')),
                ('question_en', models.TextField(blank=True, help_text='Question in English')),
                ('answer_ml', models.TextField(help_text='Answer in Malayalam')),
                ('answer_en', models.TextField(blank=True, help_text='Answer in English')),
                ('category', models.CharField(max_length=50)),
                ('keywords', models.JSONField(default=list, help_text='Keywords for matching queries')),
                ('applicable_districts', models.JSONField(blank=True, default=list)),
                ('applicable_seasons', models.JSONField(blank=True, default=list)),
                ('applicable_crops', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farming FAQ',
                'verbose_name_plural': 'Farming FAQs',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_question', models.TextField()),
                ('ai_response', models.TextField()),
                ('language', models.CharField(choices=[('ml', 'Malayalam'), ('en', 'English')], default='ml', max_length=2)),
                ('category', models.CharField(choices=[('GENERAL', 'General Query'), ('CROP_ADVICE', 'Crop Advice'), ('WEATHER', 'Weather Related'), ('PEST_CONTROL', 'Pest Control'), ('SOIL_HEALTH', 'Soil Health'), ('FERTILIZER', 'Fertilizer Advice'), ('IRRIGATION', 'Irrigation'), ('MARKET', 'Market Information'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('user_district', models.CharField(blank=True, max_length=50, null=True)),
                ('crops_mentioned', models.JSONField(blank=True, default=list)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_chatlog_user_id_18d377_idx'), models.Index(fields=['session_id', '-created_at'], name='ai_chatlog_session_6945d1_idx'), models.Index(fields=['category', '-created_at'], name='ai_chatlog_categor_d42635_idx')],
            },
        ),
    ]
